# Generated by Django 6.0.4 on 2026-04-24 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_spacedrepetition'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='source_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_courses', to='core.language'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_courses', to='core.language'),
        ),
    ]
